Algoritmo "aula1"

Var
// Seção de Declarações das variáveis 
//TIPO DE DADOS
// caractere - texto
nome : caractere
// real - decimal, numeros quebrados
valor : real
// inteiro - "valor redondo"
idade : inteiro
// logico - verdadeiro e falso, boolean
ligado : logico

// regras de variaveis
// 1 - não pode palavras dedicadas
// 2 - não pode carctere especial
// 3 - não pode acento e cedilha
// 4 - não pode começar com numero, só o numero
// 5 - não pode espaço vazios
//  * camel case - nomeComposto
//  * snake case - nome_composto
//  * upper case - NOMECOMPOSTO
//                       (maisculo)
//  * lower case - nomecomposto
//                       (minusculo)


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval("yasmin")
escreval("paz")
escreval(6+2345678)

Fimalgoritmo