Algoritmo "abidas"

Var
 opcao : inteiro

Inicio
escreval("*******************")
escreval("*******abidas******")
escreval("-------------------")
escreval("1) tenis - R$ 150,00")
escreval("2) camiseta - R$ 350,00")
escreval("3) short - R$ 99,99")
escreval("4) blusa de frio - R$ 450,99")
escreval("5) conjunto - R$ 5000,50")
escreval("6) FINALIZAR A COMPRA")
escreval("7) SAIR")
leia (opcao)

escolha (opcao)
 caso 1
  escreval ("comprando tenis")
 caso 2
  escreval ("comprando camiseta")
 caso 3
  escreval ("comprando short")
 caso 4
  escreval("comprando blusa de frio")
 caso 5
  escreval ("comprando conjunto")
  caso6
  escreval("SELECIONOU FINALIZAR")
  caso 7
  escreval("SELECIONOU SAIR")
  outrocaso
  escreval("Erro! opção inválida")
  
fimEscolha
Fimalgoritmo