Algoritmo "cadegoria de natação"

Var
idade : inteiro
Inicio
escreval("qual a sua idade?")
leia(idade)
se (idade >=5) e (idade <=7) entao
escreval("infantil A")

fimse

se (idade >=8) e (idade <=11) entao
escreval("infantil B")

fimse

se (idade >=12) e (idade <=13) entao
escreval("juvenil A")

 fimse
 
se (idade >=14) e (idade <=17) entao
escreval("juvenil B")

fimse

se (idade >=18) entao
escreval("adultos")

fimse


Fimalgoritmo
