Algoritmo "aula 4 parte 2"

Var
senha, senhaCadastrada: caractere
usuario , usuarioCadastrado : caractere

Inicio
usuarioCadastrado <- "yasminpaz"
senhaCadastrada <- "123"
escreval("qual o usuario:")
leia (usuario)
escreval("qual a senha:")
leia(senha)
se (senha = senhaCadastrada) e (usuario = usuarioCadastrado)entao

 escreval("usurio correto")
 senao
  escreval("usuario incorreto")
  fimse
  
  

Fimalgoritmo